{% set name = "trl" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 23de65a9f97c1c68161c049896829a333f0cfadeb82c2dad06fe2c0a15338378

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - rich
    - python >={{ python_min }}
    - pytorch >=1.4.0
    - transformers >=4.46.0
    - numpy >=1.18.2
    - accelerate >=0.34.0
    - datasets >=3.0.0
    - tyro >=0.5.11

test:
  imports:
    - trl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/huggingface/trl
  summary: Train transformer language models with reinforcement learning.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
