{% set name = "trl" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1e57f23ae58a088a627773a821e6337285798fac1e432b370e335c8cf894962e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch >=1.4.0
    - transformers >=4.31.0
    - numpy >=1.18.2
    - accelerate
    - datasets
    - tyro >=0.5.11

test:
  imports:
    - trl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/trl
  summary: Train transformer language models with reinforcement learning.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
