{% set name = "trl" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3e98c303dabe0ddbfe162eeddbe27a93590fc884cb4d4e4d644ac265897456d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - rich
    - python >={{ python_min }}
    - pytorch >=1.4.0
    - transformers >=4.46.0
    - numpy >=1.18.2
    - accelerate >=0.34.0
    - datasets >=2.21.0
    - tyro >=0.5.11

test:
  imports:
    - trl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/huggingface/trl
  summary: Train transformer language models with reinforcement learning.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
