schema_version: 1

context:
  name: trl
  version: 1.13.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/huggingface/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: bee1276495123e3234ffddf768ac6eea3e53ca8be016ab7894302065254486ca

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - jinja2
    - packaging >20.0
    - python >=${{ python_min }}
    - transformers >=4.56.2
    - accelerate >=1.4.0
    - datasets >=4.7.0
tests:
  - python:
      imports:
        - trl
      pip_check: true
      python_version:
        - ${{ python_min }}
        - '*'

about:
  summary: Train transformer language models with reinforcement learning.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/huggingface/trl

extra:
  recipe-maintainers:
    - jan-janssen
